version: 2

builds:
  - id: backup-route53
    binary: backup-route53
    main: ./cmd/backup-route53
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildDate={{.Date}}

brews:
  - repository:
      owner: mrtimp
      name: homebrew-formulas
    directory: Formula
    homepage: "https://github.com/mrtimp/aws-backup-route53"
    description: "Backup AWS Route 53 zones to CSV"
    commit_author:
      name: mrtimp
      email: timp@unfuddle.nz
