version: 2

builds:
  - goos:
    - linux
    - darwin
    - windows

brews:
  - repository:
      owner: mrtimp
      name: homebrew-formulas
    directory: Formula
    homepage: "https://github.com/mrtimp/aws-backup-route53"
    description: "Backup AWS Route 53 zones to CSV"
    commit_author:
      name: mrtimp
      email: timp@unfuddle.nz
